# ==============================================================================
# Quartus Prime Synopsys Design Constraint File
# Generated by OpenGateware - Gateman CLI v0.1.0
# ==============================================================================
# pocket SDC settings
# Users are recommended to modify this file to match users logic.
# Put your clock groups in here as well as any net assignments.
# ==============================================================================

# ==============================================================================
# Time Information
# ==============================================================================
set_time_format -unit ns -decimal_places 3

# ==============================================================================
# Create Clock
# ==============================================================================
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4BaddrL[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4BaddrL[4]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4DaddrL[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4DaddrL[4]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4EaddrL[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4EaddrL[4]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4HaddrL[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|BG4HaddrL[4]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|T80as:Z80A|MREQ} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|U10nRCO} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|U12H_cnt[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:U2A_A|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:U2B_B|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:U3A_A|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:U3B_B|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:spU2A_A|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:spU2A_B|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ls107:spU2B_A|q} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|pixH[1]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|pixH[2]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|pixV[0]} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|sp10_CK} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|sp11_CK} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|spnH4CA} -period 150.000 -waveform { 0.000 50.000 }
# create_clock -name {core_top:ic|exerion_fpga:excore|ttl_7474:U1D_B|Q_current[0]} -period 150.000 -waveform { 0.000 50.000 }

# ==============================================================================
# Create Generated Clock
# ==============================================================================

# ==============================================================================
# Set Clock Latency
# ==============================================================================

# ==============================================================================
# Set Clock Uncertainty
# ==============================================================================
derive_clock_uncertainty

# ==============================================================================
# Set Input Delay
# ==============================================================================

# ==============================================================================
# Set Output Delay
# ==============================================================================

# ==============================================================================
# Set Clock Groups
# ==============================================================================
# set_clock_groups -asynchronous \
#  -group { ic|exerion_fpga:excore|BG4BaddrL[1] \
#           ic|exerion_fpga:excore|BG4BaddrL[4] } \
#  -group { ic|exerion_fpga:excore|BG4DaddrL[1] \
#           ic|exerion_fpga:excore|BG4DaddrL[4] } \
#  -group { ic|exerion_fpga:excore|BG4EaddrL[1] \
#           ic|exerion_fpga:excore|BG4EaddrL[4] } \
#  -group { ic|exerion_fpga:excore|BG4HaddrL[1] \
#           ic|exerion_fpga:excore|BG4HaddrL[4] } \
#  -group { ic|exerion_fpga:excore|T80as:Z80A|MREQ } \
#  -group { ic|exerion_fpga:excore|U10nRCO } \
#  -group { ic|exerion_fpga:excore|U12H_cnt[1] } \
#  -group { ic|exerion_fpga:excore|ls107:U2A_A|q } \
#  -group { ic|exerion_fpga:excore|ls107:U2B_B|q } \
#  -group { ic|exerion_fpga:excore|ls107:U3A_A|q } \
#  -group { ic|exerion_fpga:excore|ls107:U3B_B|q } \
#  -group { ic|exerion_fpga:excore|ls107:spU2A_A|q } \
#  -group { ic|exerion_fpga:excore|ls107:spU2A_B|q } \
#  -group { ic|exerion_fpga:excore|ls107:spU2B_A|q } \
#  -group { ic|exerion_fpga:excore|pixH[1] } \
#  -group { ic|exerion_fpga:excore|pixH[2] } \
#  -group { ic|exerion_fpga:excore|pixV[0] } \
#  -group { ic|exerion_fpga:excore|sp10_CK } \
#  -group { ic|exerion_fpga:excore|sp11_CK } \
#  -group { ic|exerion_fpga:excore|spnH4CA } \
#  -group { ic|exerion_fpga:excore|ttl_7474:U1D_B|Q_current[0] }

# ==============================================================================
# Set False Path
# ==============================================================================

# ==============================================================================
# Set Multicycle Path
# ==============================================================================

# ==============================================================================
# Set Maximum Delay
# ==============================================================================

# ==============================================================================
# Set Minimum Delay
# ==============================================================================

# ==============================================================================
# Set Input Transition
# ==============================================================================

